name: DepSec

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  npm-audit-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ybiquitous/npm-audit-fix-action@v4
